### ISSUE TITLE
hi can i use this kp3 setup?

### ISSUE THREAD

**Issue by jmartens2** [dulfe/Kingroon-KP3S-Marlin#1]
as the title sez id like to try to use this with my machine. im a noob trying to install inductive probe on this machine and using bed leveling.

**Comment by dulfe** [comment]
I do not have a KP3, so I have not tested it. I did a quick check online a the KP3 is not a direct drive, so I am guessing it also has other internal differences. I would not use this firmware in a KP3.

**Comment by jmartens2** [comment]
Thank you for the response!! Have a great day!!
