### ISSUE TITLE
driver type

### ISSUE THREAD

**Issue by nebakanezzer** [dulfe/Kingroon-KP3S-Marlin#2]
I'm writing a config based off of yours. looks like you designate A4988 drivers in config.h. not sure if this has changed, but the kp3s now ships with removable TMC2225. was this the case when you drafted this, and it just worked?

**Comment by dulfe** [comment]
KP3S always used TMC2225, but the drivers were not available in Marlin when I created the configuration file. But, since they are compatible with A4988 (as per specs) I used that one and it worked fine. 

Since then I have made some changes to the printer and now it is using TMC2208 drivers.

**Comment by nebakanezzer** [comment]
thanks for your quick response. this is what I thought. I'm currently writing my own branch from marlin bugfix 2.0, but I don't see tmc2225 there either: https://github.com/nebakanezzer/Marlin/blob/Mini-Me/Marlin/Configuration.h

relevant bits:

```
 * A4988 is assumed for unspecified drivers.
 *
 * Options: A4988, A5984, DRV8825, LV8729, L6470, L6474, POWERSTEP01,
 *          TB6560, TB6600, TMC2100,
 *          TMC2130, TMC2130_STANDALONE, TMC2160, TMC2160_STANDALONE,
 *          TMC2208, TMC2208_STANDALONE, TMC2209, TMC2209_STANDALONE,
 *          TMC26X,  TMC26X_STANDALONE,  TMC2660, TMC2660_STANDALONE,
 *          TMC5130, TMC5130_STANDALONE, TMC5160, TMC5160_STANDALONE
 * :['A4988', 'A5984', 'DRV8825', 'LV8729', 'L6470', 'L6474', 'POWERSTEP01', 'TB6560', 'TB6600', 'TMC2100', 'TMC2130', 'TMC2130_STANDALONE', 'TMC2160', 'TMC2160_STANDALONE', 'TMC2208', 'TMC2208_STANDALONE', 'TMC2209', 'TMC2209_STANDALONE', 'TMC26X', 'TMC26X_STANDALONE', 'TMC2660', 'TMC2660_STANDALONE', 'TMC5130', 'TMC5130_STANDALONE', 'TMC5160', 'TMC5160_STANDALONE']
 */
```

**Comment by erstec** [comment]
TMC2225 are same protocol as TMC2208 (according https://wiki.fysetc.com/TMC2225/) and same as TMC5130 and TMC5072, as described in official datasheet https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2225_Datasheet_Rev1.11.pdf paragraph 1.2.1

Another question is: there is no UART connection to TMC on KP3S board, at least I have and need external connections to make it work. So this is why A4988 drivers was used.

**Comment by nebakanezzer** [comment]
that was something I was considering. with it configured as 2208 and no uart, wouldnt it default to stealth chop and manual vref adjustment? what external connections did you need? I'm trying to lookup the pinout, but all teh versions are different from what I have: https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/hardware

**Comment by erstec** [comment]
@nebakanezzer I just don't see any advantages to just use another driver. External connections required for UART connections, as their not routed on PCB, what, for ex., allows you to use Linear Advance, adjust current and etc.

**Comment by nebakanezzer** [comment]
linear advance and vref via code instead of manual are pretty nice features. do you just need to jump the pins on the driver to the ones next to the driver sockets on the board?

**Comment by erstec** [comment]
@nebakanezzer, my comment is just explanation why A4988 drivers was used (in my opinion) and not manual to what to do or not. It is open-source and every user can just fork any repository and do what he want and how he want.

Some lyrics: Every Marlin user have own preferences and comments like "one instead another" sounds a little bit offensive, so please be more respectfull.

I hope my position is clearly explained and this topic is closed.

**Comment by nebakanezzer** [comment]
not sure where I was offensive? was asking for advice on which pins to use if one wants to actually use the drivers as intended and not as undefined so all features can be used.
